#!/bin/bash

apt_packages=()
apt_packages+=("sudo")
apt_packages+=("git")
apt_packages+=("stow")
apt_packages+=("apt-transport-https")

#apt_packages+=("synaptic")
#apt_packages+=("firefox-esr")
#apt_packages+=("redshift-gtk")
#apt_packages+=("evince")
#apt_packages+=("ristretto")
#apt_packages+=("rclone")
#apt_packages+=("thunderbird")
#apt_packages+=("telegram-desktop")

apt_packages+=("xfce4")
apt_packages+=("xfce4-power-manager")
apt_packages+=("xfce4-terminal")
apt_packages+=("thunar-archive-plugin")
apt_packages+=("network-manager-gnome")
apt_packages+=("gvfs-backends")
#apt_packages+=("blueman")