#!/bin/bash
#
# Script name: install-code-extensions
# Description: Install my preferred Microsoft Visual Studio Code
#              extensions on Debian 10.
# Dependencies: code
# GitHub: https://github.com/ifcodesdotnet/.dotfiles
# Contributors: Ismael Fernandez

vscode_extensions=()
vscode_extensions+=("PKief.material-icon-theme")
vscode_extensions+=("jolaleye.horizon-theme-vscode")
vscode_extensions+=("ms-dotnettools.csharp")
vscode_extensions+=("ms-azuretools.vscode-docker")
vscode_extensions+=("eamodio.gitlens")
vscode_extensions+=("alefragnani.Bookmarks")

for extension in "${!vscode_extensions[@]}";
do
    sudo -u $(logname) code --install-extension ${vscode_extensions[$extension]}
done