#!/bin/bash
mkdir $HOME/dotnet-core-sdk-temp-install
wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb \
    -P $HOME/dotnet-core-sdk-temp-install

sudo dpkg -i $HOME/dotnet-core-sdk-temp-install/packages-microsoft-prod.deb

sudo apt-get update
sudo apt-get install -y apt-transport-https

sudo apt-get update
sudo apt-get install -y dotnet-sdk-3.1

sudo rm -rf $HOME/dotnet-core-sdk-temp-install