#!/bin/bash
#
# Script name: install-vscode
# Description: Install Microsoft Visual Studio Code on Debian 10, instructions
#              taken from https://code.visualstudio.com/docs/setup/linux. 
# Dependencies: gpg, apt-transport-https
# GitHub: https://github.com/ifcodesdotnet/.dotfiles
# Contributors: Ismael Fernandez

sudo echo > /dev/null 2>&1

download_vscode_debian_repository_key(){
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor > ~/packages.microsoft.gpg
}

install_vscode_debian_repository_key(){
    sudo install -o root      \
    -g root                  \
    -m 644                   \
    ~/packages.microsoft.gpg \
    /etc/apt/trusted.gpg.d/
}

delete_microsoft_repository_key(){
    rm ~/packages.microsoft.gpg
}

update_apt_sources_list(){
    if [ ! -f "/etc/apt/sources.list.d/vscode.list" ]; 
    then
        echo adding vscode debian repository link.
        sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
    fi
}

install_apt_transport_https(){
    echo installing apt-transport-https.

    sudo apt-get install -y apt-transport-https > /dev/null 2>&1
    if [ $? -ne 0 ];
    then
        echo failure installing apt-transport-https.
        exit
    fi
}

update_apt_cache(){
    echo updating apt cache.

    sudo apt update
    if [ $? -ne 0 ];
    then
        echo failure updating apt cache.
        exit
    fi
}

install_vscode(){
    echo installing code.

    sudo apt install -y code
    if [ $? -ne 0 ];
    then
        echo failure installing code.
        exit
    fi
}

download_vscode_debian_repository_key
install_vscode_debian_repository_key
delete_microsoft_repository_key
update_apt_sources_list
install_apt_transport_https
update_apt_cache
install_vscode