#!/bin/bash
#
# Script name: install-vscode
# Description: Install Microsoft Visual Studio Code on Debian 10, instructions
#              taken from https://code.visualstudio.com/docs/setup/linux. 
# Dependencies: gpg, apt-transport-https
# GitHub: https://github.com/ifcodesdotnet/.dotfiles
# Contributors: Ismael Fernandez

sudo echo > /dev/null 2>&1

echo installing vscode

wget -qO- https://packages.microsoft.com/keys/microsoft.asc |
          gpg --dearmor > ~/packages.microsoft.gpg

sudo install -o root                  \
             -g root                  \
             -m 644                   \
             ~/packages.microsoft.gpg \
             /etc/apt/trusted.gpg.d/
             
rm ~/packages.microsoft.gpg

if [ ! -f "/etc/apt/sources.list.d/vscode.list" ]; 
then
    echo adding code debian repository link.
    sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
fi

echo installing apt-transport-https.
sudo apt-get install -y apt-transport-https > /dev/null 2>&1
if [ $? -ne 0 ];
then
    echo failure installing apt-transport-https.
    exit
fi

echo updating apt cache.
sudo apt-get update > /dev/null 2>&1
if [ $? -ne 0 ];
then
    echo failure updating apt cache.
    exit
fi

echo installing code.
sudo apt-get install -y code > /dev/null 2>&1
if [ $? -ne 0 ];
then
    echo failure installing code.
    exit
fi

echo successfully installed code.