#!/bin/bash
#
# Script name: install-vscode
# Description: Install Microsoft Visual Studio Code on Debian 10, instructions
#              taken from https://code.visualstudio.com/docs/setup/linux. 
# Dependencies: gpg, apt-transport-https
# GitHub: https://github.com/ifcodesdotnet/.dotfiles
# Contributors: Ismael Fernandez

sudo echo > /dev/null 2>&1

download_microsoft_repository_key(){
    if [ ! -f /etc/apt/trusted.gpg.d/packages.microsoft.gpg ]; 
    then
        echo downloading microsoft repository key.
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc |
        gpg --dearmor > ~/packages.microsoft.gpg
    fi
}

install_microsoft_repository_key(){
    if [ -f ~/packages.microsoft.gpg ];
    then
        sudo install -o root     \
        -g root                  \
        -m 644                   \
        ~/packages.microsoft.gpg \
        /etc/apt/trusted.gpg.d/
    fi
}

delete_microsoft_repository_key(){
    if [ -f ~/packages.microsoft.gpg ];
    then
        rm ~/packages.microsoft.gpg
    fi
}

update_apt_sources_list(){
    if [ ! -f "/etc/apt/sources.list.d/vscode.list" ];
    then
        echo adding vscode repository link.
        sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
    fi
}

update_apt_cache(){
    echo updating apt cache.

    sudo apt update -y
    if [ $? -ne 0 ];
    then
        clear
        echo failure updating apt cache.
        exit
    fi
}

install_apt_transport_https(){
    echo installing apt-transport-https.

    sudo apt-get install -y apt-transport-https
    if [ $? -ne 0 ];
    then
        clear
        echo failure installing apt-transport-https.
        exit
    fi
}

install_vscode(){
    echo installing vscode.

    sudo apt install -y code
    if [ $? -ne 0 ];
    then
        clear
        echo failure installing vscode.
        exit
    fi
}

download_microsoft_repository_key
install_microsoft_repository_key
delete_microsoft_repository_key
update_apt_sources_list
update_apt_cache
install_apt_transport_https
install_vscode