#!/bin/bash

stow_targets_to_delete=()
#git
stow_targets_to_delete+=("$HOME/.gitconfig");
#bash
stow_targets_to_delete+=("$HOME/.bashrc")
stow_targets_to_delete+=("$HOME/.profile")
#xfce4
stow_targets_to_delete+=("$HOME/.config/xfce4/xfconf");
stow_targets_to_delete+=("$HOME/.config/xfce4/panel"); 
#code
stow_targets_to_delete+=("$HOME/.config/Code/User/keybindings.json");
stow_targets_to_delete+=("$HOME/.config/Code/User/settings.json");