#!/bin/bash
#
# Script name: cloud-control
# Description: Send or get updates from a cloud storage provider
# Dependencies: rclone
# GitHub: https://github.com/ifcodesdotnet/.dotfiles
# Contributors: Ismael Fernandez
# Sources:
#   https://unix.stackexchange.com/questions/31414/how-can-i-pass-a-command-line-argument-into-a-shell-script
#   https://stackoverflow.com/questions/22025793/using-getopts-to-pick-up-whole-word-flags
#   https://stackoverflow.com/questions/16654607/using-getopts-inside-a-bash-function
#   https://github.com/0xConnorRhodes/dotfiles

#source /c/Users/arbit/.dotfiles-windows/scripts/cloud/cloud-variables/cloud-storage-map
source ~/.dotfiles-windows/scripts/cloud/cloud-variables/cloud-storage-map

pull(){
  for local_directory in "${!cloud_storage_map[@]}";
  do
    rclone sync ${cloud_storage_map[$local_directory]} $local_directory -P --stats 1ms
  done
}

push(){
  for local_directory in "${!cloud_storage_map[@]}";
  do
    rclone sync $local_directory ${cloud_storage_map[$local_directory]} -P --stats 1ms
  done
}

cloud_control_usage()
{
   echo ""
   echo "Usage: $0 --push --pull"
   echo -e "\t--push Send updates to cloud"
   echo -e "\t--pull Get updates from cloud "
   exit 1
}

while [ $# -gt 0 ] ; do
  case $1 in
    --push) push ;;
    --pull) pull ;;
         *) cloud_control_usage ;;
  esac
  shift
done