#!/bin/bash
#
# Script name: cloud-control
# Description: Send or get updates from a cloud storage provider
# Dependencies: rclone
# GitHub: https://github.com/ifcodesdotnet/.dotfiles
# Contributors: Ismael Fernandez
# Sources:
#   https://unix.stackexchange.com/questions/31414/how-can-i-pass-a-command-line-argument-into-a-shell-script
#   https://github.com/0xConnorRhodes/dotfiles
#   https://rclone.org/flags/

pull(){
    local readonly directories="$(jq -r ".[]" $JSON_CONFIG)"
    local readonly timestamp=$(date +"%A-%B-%d-%l:%M-%p" | tr '[:upper:]' '[:lower:]')

    for directory in $directories; do

      rclone sync od:${directory} /home/${CURRENT_USER}/cloud/${directory} \
             --backup-dir=/home/${CURRENT_USER}/cloud/backups/${timestamp} \
             --progress \
             --stats 1s \
             --create-empty-src-dirs

    done
}

push(){
    local readonly directories="$(jq -r ".[]" $JSON_CONFIG)"

    for directory in $directories; do

      rclone sync /home/${CURRENT_USER}/cloud/${directory} od:${directory} \
             --progress \
             --stats 1s \
             --create-empty-src-dirs

    done
}

usage(){
   echo "Usage: $0 --push --pull"
   echo -e "\t--push Send updates to the cloud"
   echo -e "\t--pull Get updates from the cloud"
   exit 1
}

main(){
  readonly CURRENT_USER="$(logname)"
  readonly JSON_CONFIG="/home/${CURRENT_USER}/.dotfiles/scripts/cloud-control/directories.json"

  case $1 in
    --push) push
            ;;
    --pull) pull
            ;;
         *) usage
  esac
}

main $1