#!/bin/bash
#
# Script name: switch
# Description: dmenu-based window switcher using wmctrl.
# Dependencies: wmctrl, dmenu
# GitHub: https://github.com/ifcodesdotnet/.dotfiles/scripts/dmenu/switch
# Contributors: https://suckless.org/
# Sources:
#   https://git.suckless.org/sites/file/tools.suckless.org/dmenu/scripts/switch.html
#   https://stackoverflow.com/questions/3401183/bash-syntax-error-not-found
#   https://tools.suckless.org/dmenu/scripts/

windows=$(wmctrl -xl | tr -s '[:blank:]' | cut -d ' ' -f 3-3,5- | sed 's/^[a-zA-Z0-9-]*\.//' | sort | uniq)

# Add spaces to align the WM_NAMEs of the windows
max=$(echo "$windows" | awk '{cur=length($1); max=(cur>max?cur:max)} END{print max}')

windows=$(echo "$windows" | \
              awk -v max="$max" \
                  '{cur=length($1); printf $1; \
                    for(i=0; i < max - cur + 1; i++) printf " "; \
                    $1 = ""; printf "%s\n", $0}')

target=$(echo "$windows" | dmenu -l 10 -i -nb '#282424' -sb '#f8544c' -p switch: | tr -s '[:blank:]' | cut -d ' ' -f 2-)

if [[ -n $target ]]; then
    wmctrl -a "$target"
fi